services:
  - type: redis
    name: app-redis-primary
    region: ohio
    maxmemoryPolicy: noeviction
    ipAllowList: []

  - type: web
    name: app-server
    runtime: docker
    region: ohio
    numInstances: 1

  - type: worker
    name: app-worker
    runtime: docker
    region: ohio
    dockerCommand: node /app/node_modules/saaskitty/build/production/main.js start --service=worker
    numInstances: 1

databases:
  - name: app-pg-primary
    databaseName: primary
    ipAllowList: []
