services:
  - type: redis
    name: app-redis-primary
    region: oregon
    maxmemoryPolicy: noeviction
    ipAllowList: []

  - type: web
    name: app-storage
    healthCheckPath: /minio/health/live
    region: oregon
    runtime: image
    image:
      url: docker.io/minio/minio:latest
    dockerCommand: minio server /data --address $HOST:$PORT
    autoDeploy: false
    disk:
      name: data
      mountPath: /data
    envVars:
    - key: MINIO_ROOT_USER
      generateValue: true
    - key: MINIO_ROOT_PASSWORD
      generateValue: true
    - key: HOST
      value: "0.0.0.0"
    - key: PORT
      value: 9000

  - type: web
    name: app-server
    region: oregon
    runtime: docker
    numInstances: 1
    preDeployCommand: node /app/node_modules/saaskitty/build/production/main.js db:migrate

  - type: worker
    name: app-worker
    region: oregon
    runtime: docker
    dockerCommand: node /app/node_modules/saaskitty/build/production/main.js start --service=worker
    numInstances: 1
    preDeployCommand: node /app/node_modules/saaskitty/build/production/main.js db:migrate

databases:
  - name: app-pg-primary
    region: oregon
    databaseName: primary
    ipAllowList: []
